# Generated by Django 3.2.7 on 2021-09-16 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myBar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='SecurityCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('security_code', models.IntegerField()),
                ('account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myBar_app.mb_user')),
            ],
        ),
    ]
