# Generated by Django 3.2.7 on 2021-09-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBar_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='product_id',
        ),
    ]
