# Generated by Django 3.2.7 on 2021-10-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBar_app', '0002_alter_sale_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
