# Generated by Django 3.2.7 on 2021-10-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBar_app', '0003_alter_sale_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
